% takes a dataTensor (format of data used and generated by Gamal & John's TME code)
% and converts it into the data structure expected by Mark's jPCA code
% Preserves ordering of conditions in dataTensor and in the data structure
% Sergey Stavisky, January 5 2018
% Stanford Neural Prosthetics Translational Laboratory   
function DataOut = dataTensorToDataStruct( dataTensor, timestamps )
    for iC = 1 : size( dataTensor, 3 )
        DataOut(iC).A = dataTensor(:,:,iC); % time x neuro    
        % force column
        if size( timestamps, 2 ) ~= 1
            timestamps = timestamps';
        end
        DataOut(iC).times = timestamps;
    end
end